varReference:
- path: spec/template/spec/containers/imagePullPolicy
  kind: Deployment
- path: metadata/annotations/getambassador.io\/config
  kind: Service
- path: spec/template/spec/containers/env/value
  kind: Deployment
- path: spec/http/route/destination/host
  kind: VirtualService  
# - path: spec/template/spec/containers/0/env/3/value
#   kind: Deployment
