apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: authservice
spec:
  template:
    spec:
      volumes:
      - name: cacerts
        secret:
          secretName: "rootca-secret"
          optional: true
      containers:
      - name: authservice
        env:
        - name: CA_BUNDLE
          value: /etc/ssl/certs/cacerts.pem
        volumeMounts:
        - name: cacerts
          mountPath: /etc/ssl/certs
