apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- kustomize/kubeflow-roles
- kustomize/kubeflow-istio-resources
resources:
- seldon-edit.yaml

patchesJson6902:
- target:
    group: networking.istio.io
    version: v1alpha3
    kind: Gateway
    name: kubeflow-gateway
  patch: |-
    - op: replace
      path: /spec/servers/0/hosts
      value: ["kubeflow.kubernetes.localhost"]
    - op: replace
      path: /spec/selector
      value:
        "istio": "kubeflow-ingressgateway"
        "app": "kubeflow-ingressgateway"

namespace: "kubeflow"
commonLabels:
  kustomize.component: kubeflow-common
  app.kubernetes.io/component: "kubeflow-rbac"
  app.kubernetes.io/name: "kubeflow"
  app.kubernetes.io/version: "v1.3.0"
  app.kubernetes.io/managed-by: "superhub.io"
  app.kubernetes.io/part-of: kubeflow

generatorOptions:
  disableNameSuffixHash: true
